using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Scalar.AspNetCore;
using TmsApi.Data;


// =============================
// BUILDER
// =============================

var builder = WebApplication.CreateBuilder(args);


// =============================
// SERVICES
// =============================

// Add Controllers
builder.Services.AddControllers();


// Add EF Core PostgreSQL DbContext
builder.Services.AddDbContext<TmsDbContext>(options =>
{
    options.UseNpgsql(
        builder.Configuration.GetConnectionString("TmsDatabase")
    );

    // Display SQL generated by EF Core
    options.EnableSensitiveDataLogging();

    options.LogTo(
        Console.WriteLine,
        LogLevel.Information
    );
});


// OpenAPI / Scalar
builder.Services.AddOpenApi();


// =============================
// BUILD APPLICATION
// =============================

var app = builder.Build();


// =============================
// OPENAPI + SCALAR
// =============================

if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();

    app.MapScalarApiReference(options =>
    {
        options.Title = "TMS API Documentation";
    });
}



// =============================
// N+1 QUERY FIX TEST
// =============================

using (var scope = app.Services.CreateScope())
{
    var db = scope.ServiceProvider
        .GetRequiredService<TmsDbContext>();


    Console.WriteLine();
    Console.WriteLine("==============================");
    Console.WriteLine("N+1 QUERY FIX TEST");
    Console.WriteLine("==============================");


    var report = await db.Students
        .AsNoTracking()
        .Select(s => new
        {
            s.Name,

            EnrollmentCount = s.Enrollments.Count
        })
        .ToListAsync();



    foreach (var r in report)
    {
        Console.WriteLine(
            $"{r.Name}: {r.EnrollmentCount} enrollments"
        );
    }


    Console.WriteLine("==============================");
    Console.WriteLine("TEST COMPLETED");
    Console.WriteLine("==============================");
    Console.WriteLine();
}





// =============================
// HTTP PIPELINE
// =============================


app.UseHttpsRedirection();


app.UseAuthorization();


app.MapControllers();


// =============================
// RUN
// =============================

app.Run();

internal class Db
{
    public static object? Students { get; internal set; }
}